///////////////////////////////////////////////////////////
//  ServiceMonitorActivity.cs
//  Implementation of the Class DemoActivity
//  Generated by Enterprise Architect
//  Created on:      14-Aug-2016 7:34:51 PM
//  Original author: Apocrypha
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DemoService;
namespace DemoService {
	[Activity(Label = "Service Monitor", MainLauncher = true)]
	public class DemoActivity : Activity {

		public class DemoServiceConnection : Java.Lang.Object, IServiceConnection {

			private DemoActivity activity;
			private DemoServiceBinder binder;

			public DemoServiceConnection(){

			}

			~DemoServiceConnection(){

			}

			/// 
			/// <param name="activity"></param>
			public DemoServiceConnection(DemoActivity activity){

			}

			public DemoServiceBinder Binder{
				get;
			}

			/// 
			/// <param name="name"></param>
			/// <param name="service"></param>
			public void OnServiceConnected(ComponentName name, IBinder service){

			}

			/// 
			/// <param name="name"></param>
			public void OnServiceDisconnected(ComponentName name){

			}

		}//end DemoServiceConnection

		private DemoServiceBinder binder;
		/// <summary>
		/// com.xamarin.DemoService
		/// </summary>
		private static readonly string ComXamarinDemoservice = "com.xamarin.SoleService";
		private DemoActivity.DemoServiceConnection demoServiceConnection;
		private bool isBound = false;
		private bool isConfigurationChange = false;

		public DemoActivity(){

		}

		~DemoActivity(){

		}

		private void CheckBound(){

		}

		private void InitializeContetnt(){

		}

		/// 
		/// <param name="bundle"></param>
		protected override void OnCreate(Bundle bundle){

		}

		protected override void OnDestroy(){

		}

		/// <summary>
		/// return the service connection if there is a configuration change
		/// </summary>
		public override Java.Lang.Object OnRetainNonConfigurationInstance(){

			return null;
		}

		/// <summary>
		/// BindServiceByIntent using demoServiceConnection
		/// </summary>
		protected override void OnStart(){

		}

	}//end DemoActivity

}//end namespace DemoService