///////////////////////////////////////////////////////////
//  TimeServiceBinder.cs
//  Implementation of the Class TimeServiceBinder
//  Generated by Enterprise Architect
//  Created on:      14-Aug-2016 9:53:59 PM
//  Original author: Falcon
///////////////////////////////////////////////////////////

namespace AMailSync.Services
{
    public class TimeServiceBinder : Android.OS.Binder
    {
        private TimeService service;

        public TimeServiceBinder()
        {
        }

        ~TimeServiceBinder()
        {
        }

        ///
        /// <param name="service">change to correct service typу</param>
        public TimeServiceBinder(TimeService service)
        {
            this.service = service;
        }

        public TimeService GetService()
        {
            return service;
        }
    } //end TimeServiceBinder
} //end namespace DemoService