///////////////////////////////////////////////////////////
//  TimeServiceBinder.cs
//  Implementation of the Class TimeServiceBinder
//  Generated by Enterprise Architect
//  Created on:      14-Aug-2016 9:53:59 PM
//  Original author: Falcon
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DemoService;
using StockService;
namespace DemoService {
	public class TimeServiceBinder : Binder {

		private DemoService service;

		public TimeServiceBinder(){

		}

		~TimeServiceBinder(){

		}

		/// 
		/// <param name="service">change to correct service typr</param>
		public TimeServiceBinder(StockService service){

		}

		public DemoService GetDemoService(){

			return null;
		}

	}//end TimeServiceBinder

}//end namespace DemoService