///////////////////////////////////////////////////////////
//  TimeServiceBinder.cs
//  Implementation of the Class TimeServiceBinder
//  Generated by Enterprise Architect
//  Created on:      14-Aug-2016 9:53:59 PM
//  Original author: Falcon
///////////////////////////////////////////////////////////

using System;
using Android.App;
using Android.Util;
using System.Threading;
using Android.Content;
using Android.Widget;
using Android.OS;

namespace AMailSync
    {
	public class TimeServiceBinder : Binder {

		private TimeService service;

		public TimeServiceBinder(){

		}

		~TimeServiceBinder(){

		}

		/// 
		/// <param name="service">change to correct service typr</param>
		public TimeServiceBinder(TimeService service){

		}

		public TimeService GetTimeService(){

			return null;
		}

	}//end TimeServiceBinder

}//end namespace DemoService